### ISSUE TITLE
ESP-32 port ? 

### ISSUE THREAD

**Issue by akileos** [ThomDietrich/miflora-mqtt-daemon#1]
Hi,

 Sure not the goal of you tool, but have you considered porting it to ESP32 ? Would be nice when Pi is too far from Miflora.

**Comment by ThomDietrich** [comment]
Hey! That's definitely out of scope for this project, which is a Linux daemon developed in Python3...
However the project was developed with this problem in mind! You can throw a few Raspberry Pi 0W (13€) with the daemon running in your house to reach all Mi Flora sensors.

**Comment by akileos** [comment]
Ho didn't catch the fact the the Pi Zero-W had BLE support, is it tested yet on this board? would fit event if twice the price of ESP32, hard to compare "computer" vs MCU.
