### ISSUE TITLE
not working with 3.1.8

### ISSUE THREAD

**Issue by devchristof** [ThomDietrich/miflora-mqtt-daemon#10]
I have juste receive lastest miflora with firmware 3.1.8 its seems not working with.

its ok for my olds 2.6.2

if you have any idee

thanks :)

**Comment by ThomDietrich** [comment]
Hello @devchristof, could you please try again? Check the linked issue for a test that proves that the library also works with the firmware 3.1.8

**Comment by devchristof** [comment]
I retry, ok its working for me, but a very short range, strange.

**Comment by napoleonmm83** [comment]
I have problems to. Yesterday at my first try it was working, but now have issues.

`
[2017-12-25 10:43:06] Retrieving data from sensor "plant4" ...
connect: Operation not supported (95)
connect: Operation not supported (95)
connect: Operation not supported (95)
connect: Operation not supported (95)
[2017-12-25 10:43:36] Retrying ...
connect: Operation not supported (95)
connect: Operation not supported (95)
connect: Operation not supported (95)
connect: Operation not supported (95)
[2017-12-25 10:44:06] Failed to retrieve data from Mi Flora sensor "plant4" (C4:7C:8D:65:D9:05), success rate: 0%


`

**Comment by napoleonmm83** [comment]
i solved the problem,  i get a other bluetooth dongle and now is working

**Comment by ThomDietrich** [comment]
Great ;)
