### ISSUE TITLE
Lichtstärke in HomeKit einbinden? Rest geht

### ISSUE THREAD

**Issue by clipse2004** [ThomDietrich/miflora-mqtt-daemon#103]
Hi, 
also ich konnte mit dem MQTTT Plugin für Homebridge, die Temperatur sowie die Feuchtigkeit einbinden und anzeigen lassen. Ich habe allerdings Schwierigkeiten die Licht Intensität sowie die Bodenqualität anzeigen zu lassen, geht das nicht?
Anbei mal meine Config für die Lichtstärke:

```json
{
    "accessory": "mqttthing",
    "type": "lightSensor",
    "name": "GummibaumHelligkeit",
    "url": "http://192.178.XXX.XXX:1883",
    "topics": {
        "getBrightness": {
            "topic": "miflora/Gummibaum/getBrightness",
            "apply": "return JSON.parse(message).light"
        },
        "getBatteryLevel": {
            "topic": "miflora/Gummibaum",
            "apply": "return JSON.parse(message).battery"
        }
    }
}
```

Habt ihr nen Tipp für mich? 

Thx

**Comment by ThomDietrich** [comment]
Hallo @clipse2004,
wenn dein Code in allem weiteren korrekt ist und du mit einer ähnlichen Konfiguration die Temperatur auslesen kannst können wir dir wohl auch nicht helfen. Das beste wird sein, du stellst die Frage zusammen mit der Message vom MQTT broker im Homebridge Forum.

Bitte lass es uns wissen wenn sich herausstellt, dass wir beim miflora-mqtt-daemon etwas verbessern sollten.
