### ISSUE TITLE
Problem with adding devices

### ISSUE THREAD

**Issue by midijunk** [ThomDietrich/miflora-mqtt-daemon#11]
Hi,
sorry to bother you again. I freshly reinstalled my rpi und the miflora-mqtt-daemon. I see my devices with hcitool lescan but I can't add them. I get the following error:
```
python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py

Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
Source: https://github.com/ThomDietrich/miflora-mqtt-daemon

[2017-10-16 13:25:13] Connecting to MQTT broker ...
[2017-10-16 13:25:13] MQTT connection established

Adding sensor to device list and testing connection ...
Name:          "tomato"
Traceback (most recent call last):
  File "/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py", line 188, in <module>
    flora_poller = MiFloraPoller(mac=mac, cache_timeout=miflora_cache_timeout, retries=3, adapter=used_adapter)
TypeError: __init__() missing 1 required positional argument: 'backend'
```
Checked my config.ini but can't find a mistake. Any idea? Thanks

**Comment by ThomDietrich** [comment]
Hey, that's kind of my fault for being to eager during development. The daemon still depends on the latest development version of another component and that one changed recently, hence there is now this warning.

See:

https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/c275a279f4e56e98161de1fc56d0242ceda95390/requirements.txt#L1-L2

Workaround: Please remove the first line and uncomment the second. After that execute the pip installation again. You might need to uninstall the development version of the library first.

```
sudo pip3 uninstall miflora
sudo pip3 install -r requirements.txt
```

I'll fix the issue in the next couple of days and will keep you updated.

**Comment by midijunk** [comment]
Thank you very much, works!
