### ISSUE TITLE
Show firmware in home assistant card

### ISSUE THREAD

**Issue by brywithawhy** [ThomDietrich/miflora-mqtt-daemon#123]
Hi,
Is there a way we can show the firmware version in a home assistant card in lovelace?
New to mqtt and just got a few sensors reporting great , but would love to summarise all my sensors firmware and battery levels on my system status screen
Thanks in advance

**Comment by ThomDietrich** [comment]
Good question.

The firmware version is known to the HA "device" but it's a mystery to me how to access device attributes. Maybe @bangom knows.
Easiest workaround is probably to simply define a new mqtt sensor and to subscribe to the firmware topic.

Imho this topic is not related to this project and you should raise the question (how to access device attribute) in the Home Assistant forum. If you do please post the link to the discussion here!

**Comment by brywithawhy** [comment]
Sorry you're right, I landed at this page late at night after lots of clickthroughs. Didn't think about it being directly HA related, I'll post there. Thanks!

**Comment by ThomDietrich** [comment]
Good luck. Please add a link to the forum here
