### ISSUE TITLE
Requirements mixup

### ISSUE THREAD

**Issue by martinlindjarv** [ThomDietrich/miflora-mqtt-daemon#128]
With default installation (according to manual) requirements.txt might be wrong...

Just git pull and sudo pip3 install -r requirements.txt i gety an error:
miflora 0.6 has requirement btlewrap==0.0.8, but you'll have btlewrap 0.0.9 which is incompatible.

Tried with pip3 install --force-reinstall btlewrap==0.0.8 and everything works.

Later tried to update miflora to 0.7 in requirements and then got an error:
miflora 0.7.0 has requirement btlewrap==0.0.10, but you'll have btlewrap 0.0.9 which is incompatible.

So updated btlewrap to 0.0.10 and got it working ... (only one run for 7 sensors)

Should requirements.txt be updated ?

**Comment by ThomDietrich** [comment]
Hey Martin!
Thanks for the report. Would you like to create a PR for `btlewrap==0.0.10` and `miflora==0.7.0`?

**Comment by martinlindjarv** [comment]
I'll try... lets see what happens :)

**Comment by martinlindjarv** [comment]
Updates to latest miflora (according to https://pypi.org/project/miflora/)
