### ISSUE TITLE
Stuck sensor

### ISSUE THREAD

**Issue by dingausmwald** [ThomDietrich/miflora-mqtt-daemon#13]
Happend 3 times now, random sensor get stuck. Guess because of failed communication (like this?
 https://github.com/open-homeautomation/miflora/issues/48) and/or failed unpairing/disconnect. Restarting my Py helped. Anybody else?

**Comment by ThomDietrich** [comment]
Hey, you most certainly need to clarify "get stuck" :)
The sensor is not reachable any longer? The daemon stops working? The RPi went up in flames? 💥

**Comment by dingausmwald** [comment]
sry :D not reachable. The daemon is still running and collecting data from the other sensors.
While thinking about it, i could have restarted the daemon while connected to this sensor.. so the daemon didnt close the connection... in addition, the daemon is running in pm2... A routine where to check if the gattool is rdy was in discussion right? Or maybe the daemon could close the connections on start? Mostly its (again) my fault..

**Comment by ThomDietrich** [comment]
No connection is held open. Every polling cycle the connection to a sensor is established from zero. Did you try positioning the sensor better? The successrate in log should give you an idea.

**Comment by dingausmwald** [comment]
maybe its a problem with the bluetooth from my rpiZw. The daemon is running and suddenly no connections can be established. This time all stopped responding at 16.16pm.. the daemon is running in pm2 process manager. Had to close and restart your daemon. Weird... thanks for your work, can be closed i guess.
