### ISSUE TITLE
No module named 'unidecode'

### ISSUE THREAD

**Issue by FlorianBfr** [ThomDietrich/miflora-mqtt-daemon#143]
Hello,
My system is a Rpi 3 B+ with Debian Buster 10 32bits. When I start the script I have an error : 
Traceback (most recent call last):
  File "miflora-mqtt-daemon.py", line 14, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

I've installed "PIP3 install Unicode", but trouble is not solved.
Any idea ?

**Comment by ThomDietrich** [comment]
Seems like you missed the requirements listed in requirements.txt.

```
sudo pip3 install -r requirements.txt
```

**Comment by FlorianBfr** [comment]
Exactly I've miss this line.
Thank you
Very good job, work fine
Bye
