### ISSUE TITLE
Api changes in miflora break miflora-mqtt-daemon

### ISSUE THREAD

**Issue by derpeter** [ThomDietrich/miflora-mqtt-daemon#156]
https://github.com/basnijholt/miflora/pull/118 which made into the latest release requires to remove the retries flag from  https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/master/miflora-mqtt-daemon.py#L196

**Comment by ThomDietrich** [comment]
Thanks for the report. Care to create a PR?

**Comment by derpeter** [comment]
I can create a PR if you prefer, as the change is very minimal i thought its less effort for you without it :-).
just let me know. 

Btw thanks for the daemon very useful. Fun side node: I big bird stole one of my miflora sensors :-)

**Comment by ThomDietrich** [comment]
Fair point. I've just committed that change straight from the Github webpage :) I've also updated the requirement to https://github.com/basnijholt/miflora/releases/tag/v0.7.2

Can you confirm that everything works?

> Fun side node
Hahahaa must have been a big one!
