### ISSUE TITLE
MQTT Push - Topic not case sensitive

### ISSUE THREAD

**Issue by netcat-2000** [ThomDietrich/miflora-mqtt-daemon#160]
I use a case sensitive written topic for mqtt - in config.ini it is written with case sensitive - when mqtt push is done the broker receive it in lower case only. Other systems support case sensitive and all data are under the correct topic - but not miflora - it always has an extra topic - with the same name - but in lower case only. 
Can you fix this so the mqtt push is using case sensitive for the topic? 
Thank you
Oliver

**Comment by ThomDietrich** [comment]
Hey,
You need to be more specific. In many cases the transformation to `lower()` is intentional.

> I use a case sensitive written topic

Are you talking about the base topic? Which reporting_method?

**Comment by netcat-2000** [comment]
Hi,
i fully aggree - i was a bit lazy in details and on my mobile. I use MQTT mosquitto broker as broker together with Home Assistant - all on Docker. I am not a developer but i reviewed your code and have see all the "lower" statements. And i still use upper chars (old skool german). No worries at all - i already switch to a lowercase mqqt topic for that client and now all data are in one tenant . I really do not need to have a differentiation possibility in myflora. 
Thanks for your feedback - i think we can close this thread.
BR
