### ISSUE TITLE
Running on ESP32

### ISSUE THREAD

**Issue by MonsterD1** [ThomDietrich/miflora-mqtt-daemon#166]
As my raspi is to far away from the plants with ble plant sensor I wondered if it would be possible to get the code on a esp32 running.

**Comment by ThomDietrich** [comment]
Hey! This project depends on python and a Linux host system. A totally different world.

You should check out the passive BLE capabilities in the latest releases of Home Assistant as an alternative to the project here. In addition you can program your ESP32 with ESPHome to be a HA compatible "bluetooth repeater". If I didn't have a working setup using the project here, this is probably how I would do it these days.
