### ISSUE TITLE
When Temperature is below zero MQTT-daemon returns very high values (<6553.5)

### ISSUE THREAD

**Issue by lionhe1966** [ThomDietrich/miflora-mqtt-daemon#29]
During these cold nights my sensor measure temperatures below zero. The MiFlora App gives the right temperature, while the MQTT-daemon returns
{"conductivity": 1397, "moisture": 35, "temperature": 6553.5, "light": 66, "battery": 98}

This is clearly due to the fact that the temperature is a SIGNED integer while the Miflora-daemon interprets it as an UNSIGNED integer.

**Comment by GrRivero** [comment]
I have the same problem, exists workaround?

**Comment by ThomDietrich** [comment]
Solved with #31
