### ISSUE TITLE
Wrong negative Light Value above specific threshold.

### ISSUE THREAD

**Issue by muhkuhgh** [ThomDietrich/miflora-mqtt-daemon#33]
I don't know the exact treshold but the light value turns negative above a specific value..

11000 ok 
22000 ok
33000 ok

-2461 when it really is 112k.something

In C I would say it's an overflow cause maybe the unsigned 16bit unsigned int ends here or something.. but there are no variable types in python, or? I couldn't find the cause looking in the code on my own :(

**Comment by ThomDietrich** [comment]
More is needed to adapt to the latest miflora lib version. I am currently not able to implement the needed changes but invite everyone to do so and create a PR! This would be very much appreciated.

**Comment by muhkuhgh** [comment]
Actually I just had to replace
from miflora import GatttoolBackend 
with
from btlewrap import available_backends, BluepyBackend, GatttoolBackend, PygattBackend
and its working just fine now. Of course not using history data etc.. But just getting all recent values correctly.
