### ISSUE TITLE
Deamon stopps working if Sensor not found

### ISSUE THREAD

**Issue by JoanMCD** [ThomDietrich/miflora-mqtt-daemon#39]
Hi !
The demon works fine if the miflora sensor is in range. If not the deamon (or the underlaying library) stops working with the message:

```
Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
Source: https://github.com/ThomDietrich/miflora-mqtt-daemon

Adding sensor to device list and testing connection ...
Name:          "FloraCare01"
Traceback (most recent call last):
  File "/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py", line 218, in <module>
    flora_poller.fill_cache()
  File "/usr/local/lib/python3.5/dist-packages/miflora/miflora_poller.py", line 61, in fill_cache
    firmware_version = self.firmware_version()
  File "/usr/local/lib/python3.5/dist-packages/miflora/miflora_poller.py", line 104, in firmware_version
    res = connection.read_handle(_HANDLE_READ_VERSION_BATTERY)  # pylint: disable=no-member
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/gatttool.py", line 23, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/gatttool.py", line 253, in read_handle
    raise BluetoothBackendException("Exit read_ble, no data ({})".format(current_thread()))
btlewrap.base.BluetoothBackendException: Exit read_ble, no data (<_MainThread(MainThread, started -1225092352)>)
```

I test this by simply add a not existing mac in the config.ini
I have installed miflora v0.4. Any ideas ?

**Comment by ThomDietrich** [comment]
Thanks for the bug report!
As I am not able to do serious development right now I would very much appreciate if one of the others reading could have a look. Thanks!

**Comment by jboeddeker** [comment]
I enjoy the same. At first, i configured the service as restart=always, but that doesn't help. 

I am quite clueless regarding python, but i did a change. I added the  "BluetoothBackendException" which is raised by the backend to the "IOError" Exception handler.

Similar is in line 314. Only IOError Exception is handled, but BluetoothBackenException is raised.

**Comment by ThomDietrich** [comment]
Hey guys, I had a quick look.
You are on the right track. Simply replace IOError by the new more specific one. As I didn't check if an IOError could still occur, let's catch both.

Please replace those two lines:

https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/9cf5482e9361490e4681045f1ca1f91e3019a23a/miflora-mqtt-daemon.py#L221

https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/9cf5482e9361490e4681045f1ca1f91e3019a23a/miflora-mqtt-daemon.py#L316

by

```python
except (IOError, BluetoothBackendException)
```

**Comment by jboeddeker** [comment]
That's exactly what i did.  :-D

I am testing it currently. I will do a PR when i am confident this helps.

**Comment by JoanMCD** [comment]
@jboeddeker good job, thank you very much!!

line 16: from btlewrap import available_backends, BluepyBackend, GatttoolBackend, PygattBackend, BluetoothBackendException

**Comment by jboeddeker** [comment]
Thanks. I currently just use the import of BluetoothBackendException. Are all of these neccessary?

Line 15:
`from miflora.backends.gatttool import GatttoolBackend, BluetoothBackendException`

**Comment by JoanMCD** [comment]
hmm, no. 
I only want to hint that in comparism with the original code I have to add the `BluetoothBackendException`

`BluepyBackend `and `PygattBackend` are alternative backends. `BluepyBackend ` is more stabile as I read, but I still use `GatttoolBackend`

**Comment by ThomDietrich** [comment]
Exchanging the backend would be the main task for a next version.
If any of you wants to create a PR with the needed changes, that would be very much appreciated!

**Comment by jboeddeker** [comment]
OK, i made the changes. Works fine. But i am confused with github. (Not really used to it, still use SVN for all my projects.)

I made the changes in the version installed on my pi with openHABian. Works.
I created a fork and a branch, but this is a more recent version (some work is done to the backends). Cloned my fork, changed it and this works as well.

But how can i apply the changes to the version which was cloned to my pi by openhabian? This is a simple bugfix and people needing the bugfix, shouldn't got to a new versiona manually to obtain this.

**Comment by ThomDietrich** [comment]
In order to create a PR here you could actually just work with the GitHub provided editor. As the program is just one script file it is easy to add all changes, then create a PR based on that. After the PR was accepted and merged, you should be able to update your setup on the Pi by re-executing the openhabian-config step.

**Comment by ThomDietrich** [comment]
Hey guys, are you still working on this PR?

**Comment by insertjokehere** [comment]
I'm running into this (one of my sensors 'drifts' in and out of Bluetooth range, so I'm seeing this pretty often) - will try out the fix @jboeddeker and @JoanMCD over the next few days and put up a PR unless someone beats me to it

**Comment by Hypfer** [comment]
Whats the status on this?

**Comment by kaned** [comment]
Any update on this?

**Comment by ThomDietrich** [comment]
Deeply sorry for the delay guys. This should be solved now.

**Comment by kaned** [comment]
Thomas, thanks for adding this in and maintaining this daemon. It works great and makes it much easier to work with the MiFlora!
