### ISSUE TITLE
HomeAssistant integration is broken with HomeAssistant v0.69

### ISSUE THREAD

**Issue by insertjokehere** [ThomDietrich/miflora-mqtt-daemon#42]
(I intend to fix this myself and submit a PR, consider this a bug report so others know that the integration is not expected to work right now)

HomeAssistant v0.69 changed the schema for defining sensor objects via MQTT (see home-assistant/home-assistant#14033) which means that the objects published by this script are no longer valid

**Comment by ThomDietrich** [comment]
Okay thanks!

Btw as an alternative you could use the Homie mode.

**Comment by Stklingner** [comment]
FYI for the impatient: simply removing line 290 ("device_class":"sensor") in miflora-mqtt-daemon.py fixes the problem.

OT but useful info for HA users: you may also have to delete your DB file/data to fix this, additionally I deleted my broker's db file.

Also OT: thanks for making this Thom, works great!
