### ISSUE TITLE
Connection error with result code 2 - Connection Refused: identifier rejected.

### ISSUE THREAD

**Issue by chiefymuc** [ThomDietrich/miflora-mqtt-daemon#55]
Hello,

I'm trying the new openhab internal MQTT broker and so far all my devices are working great.

I can't get the MQTT Daemon to connect though (triple-checked correct credentials):

`
[2018-11-05 18:51:24] Connecting to MQTT broker ...
[2018-11-05 18:51:24] Connection error with result code 2 - Connection Refused: identifier rejected.
`

Looks like the broker is not happy with the client ID, see here: https://jaimyn.com.au/mqtt-connection-failed-status-codes-connack-return-codes/

But the config.ini does not allow to change the client ID. how is it chosen?

Cheers

**Comment by chiefymuc** [comment]
It seems there is no Client ID set. Can it be added?

**Comment by chiefymuc** [comment]
That works!

**Comment by ThomDietrich** [comment]
Weird! Could you please try to get log messages from moquette (the included broker) and see which client id is sent without the change?

**Comment by chiefymuc** [comment]
Hi, what log message are you talking about? I need some directions to get it - sorry, not very familiar with it.

**Comment by ThomDietrich** [comment]
I do not have a testing system at hand but surely Moquette writes log lines to the file `openhab.log. Those lines for a working and non-working client would be great

**Comment by NicoSoftware** [comment]
Had the same problem somehow, but the modified line worked out perfectly!

**Comment by Markkuuss** [comment]
> I do not have a testing system at hand but surely Moquette writes log lines to the file `openhab.log. Those lines for a working and non-working client would be great

I tested it with the original script:
https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/52e4658b40bacbe0809754ed58effc7759c3de48/miflora-mqtt-daemon.py#L155

Afterwards I looked into the openhab.log file. It says that the client ID can not be empty:
```
2019-01-05 22:55:43.995 [ERROR] [.moquette.spi.impl.ProtocolProcessor] - The MQTT client ID cannot be empty. Username=null
```

If I insert the client ID, as described, the connection will work fine.
```
mqtt_client = mqtt.Client(client_id="my_test_id")
```

**Comment by ThomDietrich** [comment]
@Markkuuss that's really strange as the documentation for the `Client` constructor is supposed to generate a random ID. I wonder if we should file an issue with paho-mqtt in addition to your PR.

**Comment by Markkuuss** [comment]
I just updated my paho-mqtt to 1.4.0. So it works, at least if I start the script directly:
```
python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py
```

When I start the Deamon I get the following message about the status:
```
● miflora.service - Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
   Loaded: loaded (/etc/systemd/system/miflora.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-01-10 18:15:49 CET; 17s ago
     Docs: https://github.com/ThomDietrich/miflora-mqtt-daemon
  Process: 3960 ExecStart=/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py (code=exited, status=1/FAILURE)
 Main PID: 3960 (code=exited, status=1/FAILURE)
   Status: "Jan 10 18:15:48 - Configuration accepted."

Jan 10 18:15:48 Raspberry systemd[1]: miflora.service: Unit entered failed state.
Jan 10 18:15:48 Raspberry systemd[1]: miflora.service: Failed with result 'exit-code'.
Jan 10 18:15:49 Raspberry systemd[1]: miflora.service: Service hold-off time over, scheduling restart.
Jan 10 18:15:49 Raspberry systemd[1]: Stopped Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.
Jan 10 18:15:49 Raspberry systemd[1]: miflora.service: Start request repeated too quickly.
Jan 10 18:15:49 Raspberry systemd[1]: Failed to start Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon.
Jan 10 18:15:49 Raspberry systemd[1]: miflora.service: Unit entered failed state.
Jan 10 18:15:49 Raspberry systemd[1]: miflora.service: Failed with result 'exit-code'.
```

Do you have any idea what that could be, @ThomDietrich?

**Comment by Markkuuss** [comment]
I changed the version in the file to 1.4.0 and run pip3 again.
https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/58aeb016fc8766b5953aa97134121046cadca17f/requirements.txt#L3

With this it also works with the mqtt client constructor without parameters as it currently is.
