### ISSUE TITLE
feature request: reporting_method=mqtt-smarthome

### ISSUE THREAD

**Issue by hobbyquaker** [ThomDietrich/miflora-mqtt-daemon#6]
Me again ;)

Would be nice to have the reporting_method `mqtt-smarthome` - see https://github.com/mqtt-smarthome/mqtt-smarthome

Changes would include: 
* no $announce topics
* default base topic: `miflora/status`
* default publish retain
* publishing on 4 topics instead of one, e.g. `miflora/status/plant1/moisture`, `miflora/status/plant2/conductivity` and so on. Payload following mqtt-smarthome architecture
* publishing `1` on `miflora/connected` when the daemon starts, `2` when a bluetooth connection is established, `0` as last-will testament.

Would be willing to do this and send you a PR if you'd like to get one :)

Regards,
Sebastian

**Comment by ThomDietrich** [comment]
Hey Sebastian,
yesterday I realized, that you missed a few spots :)

* Add your mode to the openHAB items generation function
* And/or add another export function for whatever you use instead
* Add your mode to the README
* Add yourself to AUTHORS, please add @nohum while you are at it https://github.com/ThomDietrich/miflora-mqtt-daemon/pull/3
* config: Please fix the comment for `base_topic`

Thanks!! Let me know if you are willing to fix them, otherwise I can look into some.

**Comment by hobbyquaker** [comment]
Hi Thomas!
About the openHAB items generation: normally you don't have a "monolithic" software like openHAB or similar in an mqtt-smarthome environment. That's been one of our main goals while creating mqtt-smarthome - getting rid of software like openHAB :) So I'm not sure if this is really needed....
For the rest I will create a PR, no problem.
I'm always open for discussions, whether in public or in private (you have my number) :-)
Regards,
Sebastian

**Comment by ThomDietrich** [comment]
Wow now we have to talk. 😅 
I totally disagree and would say MQTT **needs** something like openHAB. While MQTT provides the communication layer, an application like openHAB provides a rule engine, UIs and the linkage to other technologies. The important drawback of **every** single technology (be it Zwave, the Samsung TV or MQTT) is that it can't interface with others. openHAB closes that gap. Taking one step back: I know that you are already thinking about Android MQTT based UI apps or MQTT2xxx non-monolithic tools. I doubt these will ever offer the same ease of use openHAB is able to offer.
All that said, if you bring forth some counter arguments I'll invest some more thought into that.

**Comment by hobbyquaker** [comment]
hehe :) i'm at home, just call me ;) i agree that software like ioBroker or openHAB can potentially bring in some comfort - but for me the drawbacks are too big, I don't need and I don't like software like openHAB... :) The gaps you mentioned can be closed in a less opionated way too - I prefer the "KISS" principle ;)

**Comment by ThomDietrich** [comment]
I'm still in the office. Another time!

**Comment by hobbyquaker** [comment]
If you prefer chat over phone you can also find me here: https://join.slack.com/t/mqtt-smarthome/shared_invite/MjQxNDIyNjQxNzc3LTE1MDU0OTc4MzMtZDlmNWJiNGNhNA
