### ISSUE TITLE
New miflora device does not work

### ISSUE THREAD

**Issue by AnderssonPeter** [ThomDietrich/miflora-mqtt-daemon#75]
I just bought some miflora sensors from aliexpress i did buy 6 sensors but 2 of them don't work.
I can connect to them with gatttool and pull the values from them.
```
Id Version Data
7  2.7.0   64 15 32 2e 37 2e 30
8  2.7.0   64 15 32 2e 37 2e 30
9  3.2.1   64 2a 33 2e 32 2e 31
10 ?.?.?   64 13 32 2e 36 2e 35
11 3.2.1   64 2a 33 2e 32 2e 31
12 ?.?.?   64 13 32 2e 36 2e 35
```

If i decoded the data correctly they run version 2.6.5
Both 10 and 12 are the ones that don't work.

```
Id  Field Data
10  0x38  64 13 32 2e 36 2e 35
10  0x03  46 6c 6f 77 65 72 20 63 61 72 65
10  0x35  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
10  0x33  00 00
12  0x38  64 13 32 2e 36 2e 35
12  0x03  46 6c 6f 77 65 72 20 63 61 72 65
12  0x35  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
12  0x33  00 00
```
Is there someway to set the logging level to see exactly what goes wrong?
I found the following app https://play.google.com/store/apps/details?id=com.huahuacaocao.flowercare that might allow me to upgrade, but do we know to what version and if it will still work with this software?

**Comment by aqualx** [comment]
1. 'miflora-mqtt-daemon' do not do any decoding it uses [miflora library](https://github.com/open-homeautomation/miflora) for that. So in case any decoding issues just wrote in that repository. Most probably if you update firmware it will work. As I read somewhere minimum fw version is 2.6.**6**
2. With Flowercare  android application you can update only to latest firmware (you can't choose).

**Comment by AnderssonPeter** [comment]
@aqualx thanks i upgraded the firmware and it seems to read the values now!
I have a bunch of sensors stuck at 2.7.0 should i upgrade them too?

**Comment by aqualx** [comment]
There were some bluetooth connection issues fixed in newer firmwares. At least that will not hurt.

**Comment by RaymondMouthaan** [comment]
Today I received 6 mi-flora's from Banggood. All has an old version and I've updated them to version v3.1.9 with Flower Care app and all work fine with mi-flora mqtt daemon.

**Comment by AnderssonPeter** [comment]
Hmm wonder why you didn't get 3.2.1, I upgraded mine too(also got 3.1.9) and they work great so far!
