### ISSUE TITLE
not able to add additional sensors

### ISSUE THREAD

**Issue by Zacki84** [ThomDietrich/miflora-mqtt-daemon#97]
Hi 

I want to add additionals sensor in the config.ini.dist file, but when I run the python script I allways get the info:
MAC adress *** seems to be in the wrong format.

the odd thing is that my first and still working sensor has a MAC adress starting with C4:xx:xx:xx:xx:xx
the two new one have a MAC starting with 80:xx:xx:xx:xx:xx

I got all the MAC adresses from: sudo hcitool lescan

what can I do to get the new sensors working too?

THX

**Comment by CWempe** [comment]
Check the `miflora-mqtt-daemon.py` file and see if the following change is already implemented.

https://github.com/ThomDietrich/miflora-mqtt-daemon/commit/f442de94a6f5d58e45bdf01ca6c3967179c717eb#diff-9172f606e77c78bb7d20db0875b1a427

A previous version did only allow MAC addresses starting with `4C:65:A8`.
